image: docker:stable

services:
  - docker:dind

run_check:
  script:
    - docker build -t sgraph ./
    - docker run --rm -w /sgraph -t sgraph R -e "devtools::check()"
    - docker run --rm -w /sgraph -t sgraph R -e "covr::codecov(token = '$CODECOV_TOKEN')"
